# -- oh my zsh
export ZSH=/Users/stereohorse/.oh-my-zsh
ZSH_THEME=""
plugins=()
source $ZSH/oh-my-zsh.sh


# -- plugins

source ~/.zplug/init.zsh

zplug zplug/zplug, hook-build:'zplug --self-manage'
zplug wbinglee/zsh-wakatime
zplug zsh-users/zsh-syntax-highlighting, defer:2
zplug mafredri/zsh-async
zplug sindresorhus/pure, use:pure.zsh, as:theme
zplug plugins/docker,   from:oh-my-zsh

zplug load


# -- os vars

export EDITOR='nvim'

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


# -- aliases

alias play="ansible-playbook"

alias tmux="tmux -2"

# docker-compose
alias dc="docker-compose"
alias dc-restart="dc rm -sf && dc up"

alias pyg="pygmentize -g"

alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias ta="task"
alias ti="timew"

alias gst='git status'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gd='git diff'
alias gdc='git diff --cached'

alias ast='ssh asteroid'

# gradle
alias gw='./gradlew'

alias gradle9='docker run --rm -v "$PWD":/project -v "$HOME/.gradle":/home/gradle/.gradle -w /project gradle:4.0.1-jdk9 gradle --no-daemon'
alias with-gradle9='docker run --rm -v "$PWD":/project -v "$HOME/.gradle":/home/gradle/.gradle -w /project gradle:4.0.1-jdk9'
alias gw9='with-gradle9 ./gradlew --no-daemon'

# java 9
alias javac9='docker run --rm -v "$PWD":/usr/src -w /usr/src openjdk:9-b179-slim javac -verbose -g'
alias java9='docker run --rm -v "$PWD":/usr/src -w /usr/src openjdk:9-b179-slim java'
alias with-java9='docker run --rm -v "$PWD":/usr/src -w /usr/src openjdk:9-b179-slim'

# howdoi
function h() {
  howdoi -c -a $*
}

# ssh tunnelrs
function tun() {
  ssh -nNT -L $2:'localhost':$2 $1
}

# weather
alias weather='ansiweather -l Moscow,RU -a false -d true'
alias weatherforecast='ansiweather -l Moscow,RU -a false -d true -F'

# toggle day/nigth mode
function day() {
  sed -i.bak 's/set background=dark/set background=light/' $(readlink ~/.config/nvim/init.vim)
  tmux source-file ~/.tmux.solarized.light
  echo -e "\ePtmux;\e\e]1337;SetProfile=day\a\e\\"
}

function night() {
  sed -i.bak 's/set background=light/set background=dark/' $(readlink ~/.config/nvim/init.vim)
  tmux source-file ~/.tmux.solarized.dark
  echo -e "\ePtmux;\e\e]1337;SetProfile=night\a\e\\"
}


# -- app settings

ZSH_HIGHLIGHT_STYLES[path]=none

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON="$(command \which python2)"
source /usr/local/bin/virtualenvwrapper.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/.atlas ] && source ~/.atlas

export ENHANCD_FILTER=fzf

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=11'

export GOPATH=~/work/proj/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:/Users/stereohorse/.minimesos/bin

export SDKMAN_DIR="/Users/stereohorse/.sdkman"
[[ -s "/Users/stereohorse/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/stereohorse/.sdkman/bin/sdkman-init.sh"
