# -- oh my zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME=""
plugins=()
source $ZSH/oh-my-zsh.sh


# -- plugins

source ~/.zplug/init.zsh

zplug zplug/zplug, hook-build:'zplug --self-manage'
zplug wbinglee/zsh-wakatime
zplug zsh-users/zsh-syntax-highlighting, defer:2
zplug mafredri/zsh-async
zplug sindresorhus/pure, use:pure.zsh, as:theme
zplug plugins/docker, from:oh-my-zsh
zplug plugins/thefuck, from:oh-my-zsh
zplug lukechilds/zsh-nvm

zplug load


# -- os vars

export EDITOR='nvim'

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


# -- aliases

alias play="ansible-playbook"

alias tmux="tmux -2"

# docker-compose
alias dc="docker-compose"
alias dc-restart="dc down && dc up"

alias pyg="pygmentize -g"

# vi
alias v="nvim"
alias vi="nvim"
alias vim="nvim"
alias vig="nvim +Goyo"
alias vg="vig"

# emacs
alias em="emacsclient"

# git
alias gst='git status'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias gd='git diff'
alias gdc='git diff --cached'

alias ast='ssh asteroid'

# gradle
alias gw='./gradlew'

alias gradle9='docker run --rm -v "$PWD":/project -v "$HOME/.gradle":/home/gradle/.gradle -w /project gradle:4.0.1-jdk9 gradle --no-daemon'
alias with-gradle9='docker run --rm -v "$PWD":/project -v "$HOME/.gradle":/home/gradle/.gradle -w /project gradle:4.0.1-jdk9'
alias gw9='with-gradle9 ./gradlew --no-daemon'

alias clean-gw='docker run --rm -v "$PWD":/project -w /project gradle ./gradlew --no-daemon'

# java 9
alias javac9='docker run --rm -v "$PWD":/usr/src -w /usr/src openjdk:9-b179-slim javac -verbose -g'
alias java9='docker run --rm -v "$PWD":/usr/src -w /usr/src openjdk:9-b179-slim java'
alias with-java9='docker run --rm -v "$PWD":/usr/src -w /usr/src openjdk:9-b179-slim'

# corona sdk
alias corona='/Applications/Corona/Corona\ Simulator.app/Contents/MacOS/Corona\ Simulator'


# howdoi
function h() {
  howdoi -c -a $*
}

# ssh tunnels
function tun() {
  ssh -nNT -L $2:'localhost':$2 $1
}

# docker
function dbash() {
  docker exec -it $1 bash
}

function dsh() {
  docker exec -it $1 sh
}

function dlogs() {
  docker logs --tail 1000 -f $1
}

function dps() {
  docker ps
}

function dpss() {
  docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Ports}}"
}

function dpsn() {
  docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Names}}"
}

function dpsa() {
  docker ps -a
}

function dpsas() {
  docker ps -a --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"
}

function dpsan() {
  docker ps -a --format "table {{.ID}}\t{{.Image}}\t{{.Names}}"
}

# weather
alias weather='ansiweather -l Moscow,RU -a false -d true'
alias weatherforecast='ansiweather -l Moscow,RU -a false -d true -F'

# toggle day/nigth mode
function day() {
  echo 'set background=light' > "$HOME/.nvim.generated"
  tmux source-file ~/.tmux.solarized.light
  command -v osascript >/dev/null 2>&1 && osascript "$HOME/.set-macos-terminal-color" "Solarized Light"
}

function night() {
  echo 'set background=dark' > "$HOME/.nvim.generated"
  tmux source-file ~/.tmux.solarized.dark
  command -v osascript >/dev/null 2>&1 && osascript "$HOME/.set-macos-terminal-color" "Solarized Dark"
}


# -- app settings

ZSH_HIGHLIGHT_STYLES[path]=none

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

export ENHANCD_FILTER=fzf

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=11'

export GOPATH="$HOME/work/proj/go"
export PATH="$PATH:$GOPATH/bin"

export PATH="$PATH:$HOME/.minimesos/bin"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

if pyenv commands | command grep -q virtualenv-init; then
  eval "$(pyenv virtualenv-init - zsh)"
fi

eval $(thefuck --alias)

utils_dir="$HOME/.zsh-utils"
if [ -d "$utils_dir" ]; then
  export PATH="$PATH:$utils_dir"
fi

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
