# -- oh my zsh
export ZSH=/Users/stereohorse/.oh-my-zsh
ZSH_THEME=""
plugins=()
source $ZSH/oh-my-zsh.sh


# -- plugins

source ~/.zplug/init.zsh

zplug zplug/zplug, hook-build:'zplug --self-manage'
zplug wbinglee/zsh-wakatime
zplug zsh-users/zsh-syntax-highlighting, defer:2
zplug mafredri/zsh-async
zplug sindresorhus/pure, use:pure.zsh, as:theme

zplug load


# -- os vars

export EDITOR='nvim'

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8


# -- aliases

alias play="ansible-playbook"

alias tmux="tmux -2"

alias dc="docker-compose"

alias pyg="pygmentize -g"

alias v="nvim"
alias vi="nvim"
alias vim="nvim"

alias ta="task"
alias ti="timew"

alias gst='git status'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"

# howdoi
function h() {
  howdoi -c -a $*
}

alias weather='ansiweather -l Moscow,RU -a false -d true'
alias weatherforecast='ansiweather -l Moscow,RU -a false -d true -F'


# -- app settings

ZSH_HIGHLIGHT_STYLES[path]=none

export WORKON_HOME=$HOME/.virtualenvs
source /usr/local/bin/virtualenvwrapper.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/.atlas ] && source ~/.atlas

export ENHANCD_FILTER=fzf

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=11'

export SDKMAN_DIR="/Users/stereohorse/.sdkman"
[[ -s "/Users/stereohorse/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/stereohorse/.sdkman/bin/sdkman-init.sh"
